### PR TITLE
Update name and links `sailfishos-chum`→`sailfishos-chum-repo-config`

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Review by Olf0 — COMMENTED** [review]
LGTM, I hope I did not miss anything.

**Comment by rinigus** [comment]
https://build.sailfishos.org/package/show/sailfishos:chum/sailfishos-chum-gui is back online and we don't have to change it.

**Review by rinigus — APPROVED** [review]
LGTM

**Comment by mentaljam** [comment]
> @mentaljam, can you please deploy this (i.e., current state of `main` branch) at [chumrpm.netlify.app](https://chumrpm.netlify.app/).
> 
> Or is anybody else able to do this?

WIP

**Comment by mentaljam** [comment]
Done!

**Pull request merged**
