### PR TITLE
[chumrpm.netlify.app] Unify wording

### PR DESCRIPTION
**Pull request by Olf0**
… and try to enhance the expressiveness of the guidance.

### CODE REVIEW

**Comment by Olf0** [comment]
https://www.youtube.com/watch?v=4uMQIqtD6Ik :wink:

**Comment by rinigus** [comment]
If I would know that I will get the Kinks every time I cannot respond to PRs in timely manner, I may pull it for longer :) . I hope @mentaljam will respond soon - makes sense to get that web distribution channel of GUI RPM up to speed.

**Comment by Olf0** [comment]
@rinigus, I do not have the impression that @mentaljam [has the time and motivation](https://forum.sailfishos.org/t/future-of-storeman/10545) to review and merge this.  Maybe you can do that or trigger someone else to do it.
Thanks!

**Comment by rinigus** [comment]
I don't mind merging it - will do in  a moment. Let's see if it propagates automatically into the app itself.

**Comment by rinigus** [comment]
Looks like it didn't trigger update at https://chumrpm.netlify.app/ :( . How to do that, I don't know.

**Comment by mentaljam** [comment]
I will update it, sorry for ignoring

**Comment by mentaljam** [comment]
Done!

**Pull request merged**
